spring:
  application:
    name: HackathonProject
  datasource:
    url: jdbc:mysql://localhost/hackathon-project?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: sqllabs
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration, classpath:db/testdata
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  jpa:
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks